LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/SafeNavigation:
  Enabled: false

Style/EmptyMethod:
  Description: 'Checks the formatting of empty method definitions.'
  StyleGuide: '#no-single-line-methods'
  Enabled: false

HashSyntax:
  Description: "Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax\n{ :a => 1, :b => 2 }"
  EnforcedStyle: ruby19
  Enabled: true

RedundantBegin:
  Enabled: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 45

AllCops:
  Exclude:
    - bin/**/*
    - Rakefile
    - config/**/*
    - test/**/*
